spring:
  data:
    mongodb:
      database: plantdatabase
      uri: mongodb+srv://tanyachaudhary1:xS5aWqMJ6oCNmXwT@cluster0.jvsdw.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    
